### PR TITLE
fix: theme state localstorage 

### PR DESCRIPTION
**Pull request by hakimLyon**
Noticed the theme state is not saved in  `localStorage`.

### CODE REVIEW

**Comment by danestves** [comment]
If I'm not wrong is not saving on `localStorage` because is using cookies to save the current theme

**Comment by abereghici** [comment]
@hakimLyon thanks for this PR! @danestves is right, we don't need `localStorage` to save the theme, because the theme is already saved in cookies https://github.com/abereghici/remix-themes/blob/53079a6b6a0a2d49467a81acb1b8201b75363853/src/theme-server.ts#L20 and we can control it both server and client side.

**Comment by hakimLyon** [comment]
oh yeah 🙂  ,  sometimes with my safari browser, get the current theme doesn't work  well with ```cookies```. So I had t use both (```localStorage``` & ```cookies```) to solve the problem 😅.

@danestves @abereghici thanks for the comment. i appreciate that 😊.

**Comment by abereghici** [comment]
@hakimLyon there is an open issue related to safari https://github.com/abereghici/remix-themes/issues/11 , I'll investigate what goes wrong there.

**Comment by hakimLyon** [comment]
@abereghici thank you.

**Comment by abereghici** [comment]
Safari might not store the cookie if the domain property is not set or the secure flag is activated on localhost ( it should be activated for the production (SSL) environment). I updated the demo application and now it's working fine on Safari.
I believe we can close this PR :)

**Pull request closed without merging**
