### PR TITLE
feat: add `selectionMode` on ThemeProvider

### PR DESCRIPTION
**Pull request by igor-ribeiro**
The new prop accepts 2 options:

* SYSTEM (default): update the theme based on media color-scheme
* USER: disable updating the theme based color-scheme and uses the provided theme

closes: #32 #33

### CODE REVIEW

**Comment by abereghici** [comment]
@igor-ribeiro thank you for this contribution! I'm not sure if we should add a new prop to control this. I would include this change as part of the main logic. What do you think?

**Comment by igor-ribeiro** [comment]
Not sure if I understand. But I added as a prop because most of the sites give the user the option to choose light, dark or system for the color scheme, with a prop it's easier for the developer to control it.

**Comment by abereghici** [comment]
@igor-ribeiro thanks for contribution. I'll merge these changes in a dev branch. I would like to do more testing on this.

**Comment by crklan** [comment]
Any news on this?

**Comment by glassworks-projects** [comment]
also interested in progress here

**Comment by abereghici** [comment]
System mode support was added in https://github.com/abereghici/remix-themes/releases/tag/v1.4.0 
Check the example app.

**Pull request merged**
